version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: DOCKERFILE
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: 'python manage.py runserver 0.0.0.0:8000'
    container_name: auth_service
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: auth_service_db
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54322:5432'